# -*- coding: utf-8 -*-
"""generate-tweets-csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNkF79kCjICBev1Sw7G5PZzfZ83ypM4s
"""

import pandas as pd
import tweepy
import csv

#claves unicas de Twitter
consumer_key = 'XXXXXXXX'
consumer_secret= 'XXXXXX'
access_token= 'XXXXXXX' 
access_token_secret= 'XXXXXXXX'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

nombrefichero='tweetsUSA.csv'
csvFile = open(nombrefichero, 'a')
csvWriter = csv.writer(csvFile, delimiter=';')

queryESP="vacuna OR vacunas-filter:retweets"
queryUSA="vaccine OR vaccines -filter:retweets" 
language="en" #español, inglés

for tweet in tweepy.Cursor(api.search,q=queryUSA,
                           tweet_mode='extended',
                           count=100000,
                           lang=language,
                           since="2020-01-28",
                           until="2022-01-25").items():
 
        print (tweet.created_at , tweet.user.location.encode('utf-8'), tweet.full_text.encode('utf-8'), '', '')
        csvWriter.writerow([tweet.created_at, tweet.user.location.encode('utf-8'), tweet.full_text.encode('utf-8'), '', ''])  
    
    
  #  if tweet.coordinates and tweet.place.country is not None:
  #    print (tweet.created_at, tweet.user.location.encode('utf-8'), tweet.text.encode('utf-8'), tweet.coordinates, tweet.place.country)
  #    csvWriter.writerow([tweet.created_at, tweet.text.encode('utf-8'), tweet.coordinates, tweet.place.country])
  #  else:        
  #    print (tweet.created_at, tweet.user.location.encode('utf-8'), tweet.text.encode('utf-8'), '', '')
  #    csvWriter.writerow([tweet.created_at, tweet.user.location.encode('utf-8'), tweet.text.encode('utf-8'), '', ''])

   
# data=pd.read_csv('tweets.csv')

columnsList= ["date", "location", "text", "none1", "none2"]
df=pd.read_csv("tweetsUSA.csv", ';', header=None, names=columnsList)

# dffil= df[df['location'].str.contains("Espa|Spain|espa|spain")]
dffil= df[df['location'].str.contains("USA")]

dffil.to_csv('tweetsUSAfil.csv', index= False,encoding="utf-8",sep =";")